version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresinit
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    container_name: scrapy_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_spider
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    volumes:
      - ./news_crawler:/app
    depends_on:
      - postgres

volumes:
  local_pgdata:
    driver: local