FROM python:3.8
 
# Set the working directory to /usr/src/app.
WORKDIR /usr/src/app
 
# Copy the project source code from the local host to the filesystem of the container at the working directory.
COPY . /usr/src/app/
 
RUN pip3 install --no-cache-dir -r requirements.txt
RUN chmod +x /usr/src/app/run.sh

ENTRYPOINT ["/usr/src/app/run.sh"]
