version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresinit
    container_name: postgres_container
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    container_name: scrapy_container
    restart: on-failure
    environment:
      POSTGRES_CRAWL_USER: ${POSTGRES_CRAWL_USER}
      POSTGRES_DB: postgres
      POSTGRES_CRAWL_PASSWORD: ${POSTGRES_CRAWL_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - ./news_crawler:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  local_pgdata:
    driver: local